### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by eleanorkonik** [mrjackphil/obsidian-copy-search-link#1]
I fixed it for myself, but I don't know how to make a pull request. It works amazing (!!! I love it so much! !!! !) but is there any way you could delete the "turn the font red" css in case anybody else wants it?

**Comment by mrjackphil** [comment]
@eleanorkonik 
oh, sorry

It was from default sample project and I forgot to remove it.

Will remove it, thanks!)

**Comment by mrjackphil** [comment]
Remove the `styles.css` file because it's not needed. And updated README.md. Thanks @eleanorkonik
